In [2]:
!pip cache purge

Files removed: 0


In [3]:
!python3 -m pip install --upgrade nibabel nnunetv2 hiddenlayer

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 kB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.8/151.8 kB 13.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 63.6 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.4/96.4 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 69.8 MB/s eta 0:00:0000:0100:01
  Created wheel for nnunetv2: filename=nnunetv2-2.1-py3-none-any.whl size=212150 sha256=34e1c9a023f489cf60522024e93eab978c66783a38a9756c0458a6d0ecd1439d
  Stored in directory: /root/.cache/pip/wheels/1a/85/9d/8d92dac1

In [4]:
!pip uninstall -y scipy
!pip install --upgrade scipy==1.11.1

Found existing installation: scipy 1.11.1
Uninstalling scipy-1.11.1:
  Successfully uninstalled scipy-1.11.1
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.3/36.3 MB 31.8 MB/s eta 0:00:0000:0100:01
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.3
    Uninstalling scipy-1.7.3:
      Successfully uninstalled scipy-1.7.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cuml 23.6.0 requires cupy-cuda11x>=12.0.0, which is not installed.
cuml 23.6.0 requires dask==2023.3.2, but you have dask 2023.7.0 which is incompatible.
momepy 0.6.0 requires shapely>=2, but you have shapely 1.8.5.post1 which is incompatible.
pymc3 3.11.5 requires numpy<1.22.2,>=1.15.0, but you have numpy 1.23.5 which is incompatible.
pymc3 3.11.5 requires scipy<1.8.0,>=1.7.3, but you have scipy 1.11.1 which is incompatible.
ydata-profiling 4.3.1 requires scipy<1.11,>=1.4

In [5]:
!pip cache purge

Files removed: 37


In [6]:
import scipy
scipy.__version__
# del scipy

'1.11.1'

In [7]:
import torch
from huggingface_hub import login
import huggingface_hub

In [8]:
import huggingface_hub as hh
hh.login(token="TOKEN")
zip_path = hh.hf_hub_download(
    repo_id="osbm/prostate158",
    filename="nnunet_raw_folders/t2_to_anatomy/nnUNet_raw.zip",
    repo_type="dataset",
    local_dir=".",
)


Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [9]:
!unzip {zip_path} -d .
!rm {zip_path}

Archive:  ./nnunet_raw_folders/t2_to_anatomy/nnUNet_raw.zip
   creating: ./nnUNet_raw/
   creating: ./nnUNet_raw/Dataset001_Prostate158/
   creating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_11.nii.gz  
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_6.nii.gz  
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_14.nii.gz  
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_7.nii.gz  
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_15.nii.gz  
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_9.nii.gz  
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_4.nii.gz  
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_12.nii.gz  
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_17.nii.gz  
  inflating: ./nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_8.nii.gz  
  inflating: ./nnUN

In [10]:

import os
os.environ['nnUNet_raw'] = 'nnUNet_raw'
os.environ['nnUNet_preprocessed'] = 'nnUNet_preprocessed'
os.environ['nnUNet_results'] = 'nnUNet_results'


In [11]:
!nnUNetv2_plan_and_preprocess -d 1

Fingerprint extraction...
Dataset001_Prostate158
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
100%|█████████████████████████████████████████| 139/139 [00:24<00:00,  5.72it/s]
Experiment planning...
2D U-Net configuration:
{'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 32, 'patch_size': array([320, 320]), 'median_image_size_in_voxels': array([270., 270.]), 'spacing': array([0.4017857, 0.4017857]), 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [False], 'UNet_class_name': 'PlainConvUNet', 'UNet_base_num_features': 32, 'n_conv_per_stage_encoder': (2, 2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2, 2), 'num_pool_per_axis': [6, 6], 'pool_op_kernel_sizes': [[1, 1], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'unet_max_num_features': 512, 'resampling_fn_data': 'resample_data_or_seg_t

In [12]:
!nnUNetv2_train 1 3d_fullres 0 -tr nnUNetTrainer_20epochs

Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################


This is the configuration used by this training:
Configuration name: 3d_fullres
 {'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': [28, 256, 256], 'median_image_size_in_voxels': [25.0, 270.0, 270.0], 'spacing': [2.999998998641968, 0.4017857015132904, 0.4017857015132904], 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [False], 'UNet_class_name': 'PlainConvUNet', 'UNet_base_num_features': 32, 'n_conv_per_stage_encoder': [2, 2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 

In [ ]:
# !nnUNetv2_train 1 3d_fullres 1 -tr nnUNetTrainer_20epochs

In [13]:
!nnUNetv2_find_best_configuration 1 -c "3d_fullres" --disable_ensembling -tr nnUNetTrainer_20epochs -f 0


***All results:***
nnUNetTrainer_20epochs__nnUNetPlans__3d_fullres: 0.7910807565880633

*Best*: nnUNetTrainer_20epochs__nnUNetPlans__3d_fullres: 0.7910807565880633

***Determining postprocessing for best model/ensemble***
Removing all but the largest foreground region did not improve results!
Results were improved by removing all but the largest component for 1. Dice before: 0.85983 after: 0.85985
Removing all but the largest component for 2 did not improve results! Dice before: 0.72233 after: 0.72223

***Run inference like this:***

nnUNetv2_predict -d Dataset001_Prostate158 -i INPUT_FOLDER -o OUTPUT_FOLDER -f  0 -tr nnUNetTrainer_20epochs -c 3d_fullres -p nnUNetPlans

***Once inference is completed, run postprocessing like this:***

nnUNetv2_apply_postprocessing -i OUTPUT_FOLDER -o OUTPUT_FOLDER_PP -pp_pkl_file nnUNet_results/Dataset001_Prostate158/nnUNetTrainer_20epochs__nnUNetPlans__3d_fullres/crossval_results_folds_0/postprocessing.pkl -np 8 -plans_json nnUNet_results/Dataset001_

In [14]:
!nnUNetv2_predict -i "nnUNet_raw/Dataset001_Prostate158/imagesTs" -o "outputs" -d 1 -c "3d_fullres" --save_probabilities -f 0 -tr nnUNetTrainer_20epochs


#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 19 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 19 cases that I would like to predict
using pin_memory on device 0

Predicting PROSTATE_1:
perform_everything_on_gpu: True
Prediction done, transferring to CPU if needed
sending off prediction to background worker for resampling and export
done with PROSTATE_1

Predicting PROSTATE_10:
perform_everything_on_gpu: True
Prediction done, transferring to CPU if needed
sending off prediction to background worker for resampling and export
done with PROSTATE_10

Predicting PROST

In [15]:
!nnUNetv2_apply_postprocessing -i outputs -o outputs_post_processed -pp_pkl_file nnUNet_results/Dataset001_Prostate158/nnUNetTrainer_20epochs__nnUNetPlans__3d_fullres/crossval_results_folds_0/postprocessing.pkl -np 8 -plans_json nnUNet_results/Dataset001_Prostate158/nnUNetTrainer_20epochs__nnUNetPlans__3d_fullres/crossval_results_folds_0/plans.json

In [ ]:
from huggingface_hub import HfApi
api = HfApi()
repo_name = "osbm/prostate128_t2_anatomy_nnUNet_3d_fullres_20_epoch"
from huggingface_hub import create_repo
create_repo(
    repo_id=repo_name, 
    private=False,
    exist_ok=True,
    repo_type="dataset",
)
api.upload_folder(
    folder_path="nnUNet_results",
    path_in_repo="nnUNet_results",
    repo_id=repo_name,
    repo_type="dataset",
)
api.upload_folder(
    folder_path="nnUNet_preprocessed",
    repo_id=repo_name,
    path_in_repo="nnUNet_preprocessed",
    repo_type="dataset",
)
api.upload_folder(
    folder_path="outputs",
    path_in_repo="outputs",
    repo_id=repo_name,
    repo_type="dataset",
)

api.upload_folder(
    folder_path="outputs_post_processed",
    path_in_repo="outputs_post_processed",
    repo_id=repo_name,
    repo_type="dataset",
)

In [28]:
import nibabel as nib
import numpy as np
import pandas as pd
def DICE_COE(mask1, mask2, class_id):
    mask1 = mask1 == class_id
    mask2 = mask2 == class_id
    
    intersect = np.sum(mask1 * mask2)
    mask1_sum = np.sum(mask1)
    mask2_sum = np.sum(mask2)
    
    dice = (2 * intersect) / (mask1_sum + mask2_sum)
    dice = round(dice, 3)  # for easy reading
    return dice

scores = []
for i in range(19):
    prediction = nib.load(f"outputs_post_processed/PROSTATE_{i+1}.nii.gz").get_fdata()
    ground_truth = nib.load(f"nnUNet_raw/Dataset001_Prostate158/labelsTs/PROSTATE_{i+1}.nii.gz").get_fdata()

    for class_id in [0, 1, 2]:  # Loop over each class
        dice = DICE_COE(prediction, ground_truth, class_id)
        scores.append(dice)

scores = np.array(scores).reshape(19, 3)

df = pd.DataFrame(scores)
df.columns = ["background-dice", "inner-prostate-dice", "outer-prostate-dice"]
df.insert(0, "image-id", np.arange(1, 20))
df.to_csv("results.csv", index=False)

print("DICE scores:\n", scores.reshape(19, 3))
print("Mean DICE scores:", np.mean(scores.reshape(19, 3), axis=0))



DICE scores:
 [[0.99  0.829 0.803]
 [0.994 0.906 0.778]
 [0.991 0.917 0.715]
 [0.995 0.843 0.731]
 [0.993 0.906 0.763]
 [0.995 0.855 0.753]
 [0.994 0.893 0.764]
 [0.996 0.872 0.786]
 [0.996 0.867 0.736]
 [0.987 0.822 0.646]
 [0.996 0.845 0.829]
 [0.994 0.847 0.794]
 [0.994 0.842 0.755]
 [0.996 0.861 0.839]
 [0.995 0.897 0.793]
 [0.995 0.778 0.58 ]
 [0.996 0.878 0.789]
 [0.989 0.855 0.577]
 [0.995 0.899 0.493]]
Mean DICE scores: [0.99373684 0.86378947 0.73284211]
